#!/usr/bin/env bash

# Add devshell setup to the bash shell
echo 'eval "$(direnv hook bash)"' >> /home/vscode/.bashrc
# Snowsql setup 
# It's being used for cli and extension authentication
mkdir -p ~/.snowsql
# TODO: research user secrets in GH?
cat <<EOF > ~/.snowsql/config
[connections.sfguide-scala]
accountname = myaccount
username = myusername
password = mypassword
rolename = HOL_ROLE
warehousename = HOL_WH
dbname = HOL_DB
EOF

# Whitelist the workspace 
mkdir -p ~/.config/direnv
cat <<EOF > ~/.config/direnv/direnv.toml
[whitelist]
prefix = ["/workspaces"]
EOF
